GET http://localhost:5000/posts

###

POST http://localhost:5000/posts
Content-Type: application/json

{
    "title": "test5",
    "text": "test"
}

###

DELETE http://localhost:5000/posts/608028240340eb0a98452eb9

###

PUT http://localhost:5000/posts/608028240340eb0a98452eb9
Content-Type: application/json

{
    "title": "hej gustav",
    "text": "hej gustav"
}

###

GET http://localhost:5000/users


###

POST http://localhost:5000/register
Content-Type: application/json

{
    "email": "anton",
    "password": "12345"
}

###

POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "gustav",
    "password": "1234567"
}

###

DELETE http://localhost:5000/logout
